In [1]:
import json

with open('train.json') as json_data:
    d = json.load(json_data)

In [2]:
type(d)

dict

In [3]:
for k in d:
    print k

listing_id
interest_level
display_address
description
created
price
bedrooms
longitude
photos
manager_id
latitude
bathrooms
building_id
street_address
features

In [4]:
d['price']

{u'110554': 2995,
 u'11542': 1950,
 u'11543': 1850,
 u'11540': 2400,
 u'11541': 2500,
 u'11547': 2525,
 u'11545': 5300,
 u'89379': 3000,
 u'11549': 3300,
 u'91138': 2700,
 u'83893': 2550,
 u'19399': 1675,
 u'19398': 4255,
 u'5983': 3600,
 u'5987': 3195,
 u'5984': 4040,
 u'103549': 2250,
 u'82449': 3250,
 u'82448': 2700,
 u'116664': 2623,
 u'73392': 3500,
 u'103541': 2530,
 u'82441': 4048,
 u'82440': 1425,
 u'82446': 4000,
 u'58140': 3495,
 u'113992': 2295,
 u'120128': 5183,
 u'120120': 3000,
 u'120121': 1600,
 u'120123': 1925,
 u'120124': 3995,
 u'113011': 2595,
 u'113016': 2789,
 u'113017': 3000,
 u'88395': 5300,
 u'82990': 5000,
 u'82993': 1600,
 u'82994': 6300,
 u'82997': 2295,
 u'82996': 2500,
 u'46137': 2695,
 u'46136': 4190,
 u'46133': 2895,
 u'89372': 2250,
 u'46131': 3600,
 u'102810': 3585,
 u'89373': 2300,
 u'97152': 6295,
 u'97151': 2875,
 u'97155': 2500,
 u'89375': 5000,
 u'102814': 13500,
 u'89377': 2495,
 u'102815': 2700,
 u'19972': 5405,
 u'272': 2500,
 u'19970': 1625,
 u'16709': 1500,
 u'275': 3785,
 u'277': 10800,
 u'279': 2150,
 u'19979': 2400,
 u'19978': 2900,
 u'16701': 3490,
 u'80592': 4250,
 u'80591': 3995,
 u'16702': 3600,
 u'88023': 3700,
 u'88020': 2012,
 u'12018': 6295,
 u'88024': 3425,
 u'12015': 1900,
 u'88029': 2695,
 u'12016': 4200,
 u'101358': 2395,
 u'67177': 1995,
 u'17258': 5600,
 u'52469': 2800,
 u'100014': 7995,
 u'101359': 3075,
 u'64670': 3200,
 u'100013': 3350,
 u'17250': 2500,
 u'119867': 1600,
 u'52463': 5195,
 u'64678': 3295,
 u'52465': 2100,
 u'52467': 6850,
 u'53739': 2895,
 u'10708': 3375,
 u'63020': 1900,
 u'122338': 1800,
 u'9258': 2495,
 u'9256': 3250,
 u'9257': 3515,
 u'9254': 2125,
 u'53730': 3119,
 u'10706': 3995,
 u'10705': 3050,
 u'9251': 2600,
 u'46793': 5600,
 u'46792': 2690,
 u'46791': 6150,
 u'46797': 3600,
 u'46795': 2250,
 u'21615': 2000,
 u'21617': 2895,
 u'21616': 2399,
 u'101351': 1995,
 u'101357': 2700,
 u'69170': 4500,
 u'69173': 4795,
 u'69174': 5550,
 u'69175': 2675,
 u'69176': 2150,
 u'69177': 2950,
 u'69178': 9166,
 u'69179': 2900,
 u'80271': 3350,
 u'45442': 6400,
 u'45440': 2995,
 u'45441': 2990,
 u'44798': 1625,
 u'62369': 2650,
 u'70535': 3450,
 u'44792': 2700,
 u'44794': 2450,
 u'19392': 5995,
 u'46868': 12000,
 u'58079': 6200,
 u'19391': 3500,
 u'46861': 2900,
 u'20155': 2225,
 u'46863': 3295,
 u'46862': 5595,
 u'46866': 2500,
 u'116314': 2200,
 u'58707': 3495,
 u'90311': 3800,
 u'90315': 4310,
 u'90317': 7150,
 u'90319': 3785,
 u'115334': 2400,
 u'115592': 3375,
 u'112951': 2950,
 u'112953': 3599,
 u'112954': 5650,
 u'103543': 3500,
 u'112957': 2400,
 u'114225': 3300,
 u'13058': 3350,
 u'13059': 2400,
 u'103547': 6461,
 u'118802': 2975,
 u'13053': 5000,
 u'13050': 1300,
 u'13051': 2375,
 u'13056': 2300,
 u'13055': 2325,
 u'54171': 2195,
 u'54172': 2400,
 u'54175': 2600,
 u'87654': 2199,
 u'94548': 2700,
 u'62087': 2950,
 u'62083': 3000,
 u'62082': 3100,
 u'20259': 4000,
 u'20250': 2575,
 u'20256': 1250,
 u'20257': 4431,
 u'20255': 3895,
 u'40966': 3499,
 u'40964': 3700,
 u'40965': 5695,
 u'44423': 2200,
 u'29768': 2500,
 u'29764': 3542,
 u'29767': 3200,
 u'44429': 5000,
 u'29762': 2800,
 u'1177': 3600,
 u'1176': 2750,
 u'1171': 3850,
 u'1170': 4676,
 u'23506': 2500,
 u'23503': 1800,
 u'23502': 3900,
 u'1179': 4390,
 u'83761': 4800,
 u'27619': 3800,
 u'27618': 3500,
 u'27617': 4700,
 u'27615': 2750,
 u'27611': 2550,
 u'97939': 2895,
 u'97022': 2500,
 u'59038': 4025,
 u'89370': 3900,
 u'59033': 2400,
 u'97933': 2700,
 u'97932': 2200,
 u'97934': 2350,
 u'59034': 5400,
 u'97936': 5800,
 u'2967': 2450,
 u'118891': 3700,
 u'109977': 10500,
 u'12833': 8750,
 u'12832': 2000,
 u'12837': 2795,
 u'12836': 1660,
 u'12835': 4395,
 u'65880': 2405,
 u'8547': 3400,
 u'8546': 7200,
 u'8540': 2450,
 u'86504': 3000,
 u'626': 1925,
 u'92262': 2050,
 u'92263': 4015,
 u'92260': 3400,
 u'74016': 3300,
 u'92264': 1300,
 u'119046': 2695,
 u'119045': 2690,
 u'66502': 1800,
 u'66503': 2850,
 u'50417': 5700,
 u'66120': 5250,
 u'50414': 2915,
 u'55622': 3600,
 u'55621': 3399,
 u'55627': 3000,
 u'55624': 6275,
 u'52811': 2900,
 u'52810': 2550,
 u'52813': 2500,
 u'52812': 2200,
 u'52814': 4500,
 u'22679': 1500,
 u'22676': 2850,
 u'52818': 2895,
 u'22674': 2195,
 u'22675': 15000,
 u'22672': 3950,
 u'111547': 4195,
 u'111544': 8795,
 u'22671': 2690,
 u'60902': 3100,
 u'60903': 5000,
 u'60901': 2350,
 u'60906': 5500,
 u'88393': 4200,
 u'26568': 3695,
 u'60905': 2725,
 u'26566': 4050,
 u'26567': 2142,
 u'26564': 2300,
 u'26565': 4700,
 u'26560': 3250,
 u'75530': 1998,
 u'75533': 4640,
 u'65268': 3150,
 u'75537': 2850,
 u'75536': 2750,
 u'75539': 2600,
 u'65267': 3000,
 u'63793': 4995,
 u'116227': 4870,
 u'393': 2600,
 u'392': 4750,
 u'92884': 2650,
 u'390': 2395,
 u'397': 3030,
 u'396': 2600,
 u'92880': 2450,
 u'394': 1900,
 u'398': 2575,
 u'59734': 2900,
 u'114444': 3250,
 u'114447': 3500,
 u'114448': 4595,
 u'32224': 4100,
 u'32225': 6995,
 u'32226': 3764,
 u'32221': 2450,
 u'32222': 2500,
 u'104279': 1895,
 u'104276': 3950,
 u'104277': 3425,
 u'93137': 5000,
 u'93130': 1802,
 u'104270': 1780,
 u'93132': 1950,
 u'27896': 3295,
 u'98109': 3400,
 u'98108': 1950,
 u'3748': 2000,
 u'75288': 2600,
 u'3746': 6395,
 u'75286': 3850,
 u'3745': 2750,
 u'58709': 4050,
 u'3743': 2850,
 u'75281': 1900,
 u'41063': 5200,
 u'57665': 2975,
 u'57667': 4995,
 u'57669': 1856,
 u'57668': 5800,
 u'99853': 3100,
 u'111339': 2495,
 u'98641': 2200,
 u'52102': 3600,
 u'52100': 2400,
 u'52107': 3295,
 u'52105': 2850,
 u'105630': 2700,
 u'105633': 3190,
 u'105635': 2250,
 u'105634': 2400,
 u'105637': 1650,
 u'73859': 1813,
 u'102943': 2600,
 u'102944': 4595,
 u'60014': 3625,
 u'63364': 2625,
 u'60017': 1710,
 u'60011': 4750,
 u'113148': 8000,
 u'113149': 5600,
 u'113144': 5000,
 u'113145': 3600,
 u'113140': 2000,
 u'113141': 1550,
 u'21930': 1900,
 u'21931': 2100,
 u'21932': 3425,
 u'21934': 2400,
 u'21935': 7200,
 u'21937': 2100,
 u'114890': 3164,
 u'115498': 4750,
 u'99992': 2595,
 u'99994': 2200,
 u'57083': 4955,
 u'112944': 4550,
 u'19976': 2900,
 u'6819': 2895,
 u'15709': 2500,
 u'102362': 2350,
 u'102360': 2250,
 u'15700': 5500,
 u'6810': 2295,
 u'15703': 5400,
 u'91957': 3460,
 u'102369': 3800,
 u'107702': 2725,
 u'9754': 4600,
 u'9753': 3345,
 u'80596': 2395,
 u'75301': 1850,
 u'80595': 3300,
 u'9759': 5500,
 u'79400': 2095,
 u'37305': 3200,
 u'37306': 5700,
 u'37307': 1850,
 u'37301': 1995,
 u'24141': 2650,
 u'80593': 4900,
 u'91952': 4875,
 u'120495': 1925,
 u'81405': 3195,
 u'112237': 3550,
 u'80590': 5254,
 u'112231': 2000,
 u'59950': 2895,
 u'59953': 2775,
 u'11848': 2600,
 u'59954': 2600,
 u'59957': 3795,
 u'58938': 2950,
 u'37077': 1600,
 u'88026': 2350,
 u'33754': 3000,
 u'18536': 6780,
 u'68346': 4800,
 u'68347': 3550,
 u'102106': 5695,
 u'88028': 2025,
 u'67379': 2900,
 u'67370': 5300,
 u'69727': 3450,
 u'67372': 5882,
 u'108105': 3535,
 u'102105': 2599,
 u'108102': 4800,
 u'108103': 3300,
 u'100016': 3600,
 u'64675': 2600,
 u'102101': 7769,
 u'30334': 3645,
 u'30335': 3600,
 u'30337': 1850,
 u'30331': 3100,
 u'30332': 1650,
 u'76167': 2795,
 u'76166': 4000,
 u'88983': 4790,
 u'76163': 5000,
 u'76162': 3200,
 u'76161': 3200,
 u'44805': 3295,
 u'49165': 3375,
 u'92602': 3478,
 u'10251': 2400,
 u'119865': 3677,
 u'72394': 2195,
 u'72396': 2150,
 u'119866': 2690,
 u'72390': 3450,
 u'100137': 3200,
 u'103701': 2200,
 u'69720': 3800,
 u'119861': 2950,
 u'100136': 2100,
 u'100139': 4500,
 u'115276': 3100,
 u'91219': 7495,
 u'111951': 4295,
 u'100138': 2700,
 u'91212': 2350,
 u'119862': 1775,
 u'91216': 2600,
 u'111958': 1795,
 u'91215': 7375,
 u'104715': 2150,
 u'35219': 2450,
 u'104714': 2680,
 u'35216': 5095,
 u'35217': 2650,
 u'63026': 6335,
 u'23267': 2800,
 u'23265': 2425,
 u'88552': 2795,
 u'101709': 2800,
 u'101947': 2650,
 u'108024': 3200,
 u'114782': 5000,
 u'23269': 3650,
 u'87901': 4265,
 u'87902': 2870,
 u'87905': 2545,
 u'87904': 4825,
 u'87906': 3520,
 u'95797': 1825,
 u'53732': 3100,
 u'105253': 2095,
 u'10701': 5895,
 u'9255': 3299,
 u'43850': 4100,
 u'43857': 1300,
 u'43855': 2750,
 u'43854': 5000,
 u'95790': 3700,
 u'93960': 4200,
 u'6778': 11000,
 u'6779': 3350,
 u'6774': 4900,
 u'6777': 5490,
 u'6772': 3450,
 u'107286': 6150,
 u'92744': 2900,
 u'69298': 2200,
 u'73443': 3300,
 u'107283': 6412,
 u'92743': 6200,
 u'73440': 3800,
 u'49569': 3875,
 u'9333': 5990,
 u'73449': 4200,
 u'73448': 3049,
 u'61475': 3275,
 u'98755': 2950,
 u'49565': 3725,
 u'46799': 1700,
 u'84221': 1800,
 u'55202': 2395,
 u'121546': 2350,
 u'117197': 3150,
 u'109316': 3300,
 u'108413': 2500,
 u'81998': 4800,
 u'81995': 4985,
 u'81996': 4500,
 u'42810': 4200,
 u'85678': 2475,
 u'42812': 4600,
 u'42815': 2100,
 u'42818': 2995,
 u'42819': 2750,
 u'85672': 1850,
 u'85675': 2999,
 u'116308': 3100,
 u'5056': 4400,
 u'5050': 2450,
 u'64906': 4315,
 u'38563': 2700,
 u'38564': 1750,
 u'64905': 6235,
 u'70138': 3155,
 u'70137': 2695,
 u'70132': 4095,
 u'119806': 4500,
 u'64903': 4350,
 u'118888': 1900,
 u'18894': 10000,
 u'116614': 3000,
 u'18899': 2695,
 u'18898': 1850,
 u'122016': 3400,
 u'122017': 6495,
 u'122013': 2250,
 u'122010': 2430,
 u'120776': 2700,
 u'87295': 1850,
 u'87294': 6200,
 u'98592': 3500,
 u'123949': 4695,
 u'44222': 4450,
 u'36178': 2395,
 u'36179': 2995,
 u'44227': 1800,
 u'36174': 1775,
 u'36175': 3250,
 u'36177': 2300,
 u'36171': 3350,
 u'18769': 4500,
 u'98494': 2750,
 u'89949': 2700,
 u'89948': 3950,
 u'33529': 2699,
 u'113318': 2550,
 u'89943': 1850,
 u'108840': 4095,
 u'18763': 2700,
 u'18762': 2600,
 u'33520': 5100,
 u'108844': 3750,
 u'18767': 4500,
 u'33523': 2100,
 u'41543': 4000,
 u'41542': 3095,
 u'87125': 2700,
 u'87123': 1550,
 u'69833': 6350,
 u'41545': 1195,
 u'41549': 3800,
 u'69832': 3250,
 u'83635': 3000,
 u'83631': 4800,
 u'94139': 2650,
 u'71777': 2195,
 u'71776': 3020,
 u'71775': 4500,
 u'71773': 3825,
 u'71772': 3625,
 u'71779': 2800,
 u'8035': 2900,
 u'8030': 3017,
 u'8033': 3995,
 u'76201': 2675,
 u'104336': 3995,
 u'58075': 1813,
 u'12588': 3250,
 u'12583': 2350,
 u'12582': 2245,
 u'12581': 4290,
 u'12580': 5040,
 u'44913': 4390,
 u'44912': 3395,
 u'86654': 1550,
 u'86655': 2704,
 u'86652': 3300,
 u'44915': 4700,
 u'44914': 3795,
 u'95960': 2950,
 u'95961': 7799,
 u'123053': 1900,
 u'95964': 2695,
 u'95965': 3200,
 u'93846': 2495,
 u'86659': 3570,
 u'89491': 1345,
 u'89490': 2785,
 u'89493': 2960,
 u'89492': 5850,
 u'89495': 5000,
 u'106086': 3195,
 u'109368': 2400,
 u'109903': 3570,
 u'88720': 3795,
 u'88721': 4095,
 u'88722': 2495,
 u'88724': 6625,
 u'88725': 1700,
 u'65069': 3495,
 u'65065': 5870,
 u'65061': 2350,
 u'76079': 3290,
 u'75059': 3450,
 u'13989': 2590,
 u'120623': 3000,
 u'120622': 3800,
 u'13980': 4650,
 u'13981': 2640,
 u'120625': 2318,
 u'77664': 3295,
 u'75053': 2595,
 u'75050': 3450,
 u'77661': 2100,
 u'69693': 2195,
 u'81562': 3355,
 u'81565': 5900,
 u'81564': 3650,
 u'69697': 4500,
 u'81566': 3875,
 u'13678': 3495,
 u'13679': 3645,
 u'89230': 2875,
 u'43338': 3754,
 u'43339': 2000,
 u'43336': 2475,
 u'119560': 2700,
 u'43334': 4500,
 u'43335': 3941,
 u'89239': 3300,
 u'16002': 2100,
 u'96439': 3200,
 u'96438': 2200,
 u'5869': 1900,
 u'96433': 2450,
 u'96432': 2495,
 u'5866': 4750,
 u'96436': 3295,
 u'96434': 2100,
 u'56842': 4395,
 u'56843': 3100,
 u'56840': 5590,
 u'56841': 2870,
 u'17359': 6000,
 u'56847': 2995,
 u'56844': 3570,
 u'17355': 1495,
 u'52344': 2550,
 u'17357': 5925,
 u'17351': 6500,
 u'17350': 3295,
 u'17353': 6400,
 u'17352': 3500,
 u'90871': 3550,
 u'90870': 2600,
 u'96747': 4250,
 u'90872': 4100,
 u'90874': 4525,
 u'60258': 5950,
 u'120088': 2595,
 u'60256': 3450,
 u'60257': 5200,
 u'60254': 3295,
 u'60255': 2950,
 u'120082': 1975,
 u'60250': 55000,
 u'60251': 2900,
 u'94670': 7529,
 u'123059': 2885,
 u'121978': 4295,
 u'2231': 4350,
 u'19588': 4000,
 u'19586': 3295,
 u'19584': 7500,
 u'121974': 1195,
 u'19583': 1375,
 u'121976': 5123,
 u'19581': 2100,
 u'64007': 2200,
 u'64006': 4200,
 u'81387': 2825,
 u'52698': 5000,
 u'69031': 2400,
 u'20868': 5970,
 u'60782': 3650,
 u'60783': 2375,
 u'52693': 2700,
 u'20864': 2600,
 u'20866': 3790,
 u'52697': 2350,
 u'60789': 2950,
 u'20862': 3650,
 u'118305': 2600,
 u'118304': 6000,
 u'118300': 4000,
 u'5937': 2050,
 u'109360': 3745,
 u'5936': 2599,
 u'88214': 2395,
 u'51926': 2695,
 u'114360': 3250,
 u'86427': 2895,
 u'49159': 1810,
 u'49156': 2900,
 u'45639': 1900,
 u'99525': 2200,
 u'48209': 2995,
 u'48208': 3200,
 u'90291': 2550,
 u'90290': 2464,
 u'99522': 2995,
 u'48202': 2400,
 u'45633': 2350,
 u'45632': 3095,
 u'48207': 3790,
 u'86426': 4700,
 u'45636': 2500,
 u'7944': 2800,
 u'9190': 5975,
 u'7946': 2965,
 u'7942': 2250,
 u'7943': 4765,
 u'9199': 2960,
 u'9198': 3650,
 u'42177': 12630,
 u'42175': 1850,
 u'42174': 4200,
 u'42173': 2990,
 u'42172': 2800,
 u'42171': 3125,
 u'16914': 3200,
 u'51928': 2495,
 u'16916': 3975,
 u'80382': 2400,
 u'63787': 3475,
 u'97470': 3595,
 u'12208': 3200,
 u'12209': 2895,
 u'97476': 3475,
 u'97478': 2895,
 u'12207': 13500,
 u'12200': 2300,
 u'12201': 4730,
 u'12202': 2100,
 u'12683': 3650,
 u'90120': 1750,
 u'90127': 2375,
 u'63257': 5800,
 u'29359': 2996,
 u'53568': 3479,
 u'63254': 2500,
 u'63253': 3685,
 u'121023': 2000,
 u'63251': 6725,
 u'63250': 2100,
 u'29350': 2565,
 u'29351': 14500,
 u'53560': 3350,
 u'10511': 3200,
 u'53566': 2200,
 u'29356': 2800,
 u'29357': 2790,
 u'54691': 2950,
 u'54695': 3500,
 u'54697': 3688,
 u'8861': 4000,
 u'21404': 14000,
 u'54698': 1925,
 u'21407': 5000,
 u'8868': 5550,
 u'112955': 5200,
 u'62786': 4450,
 u'62787': 4500,
 u'62784': 3750,
 u'62789': 1850,
 u'91349': 2600,
 u'26836': 2500,
 u'97657': 1700,
 u'26830': 2525,
 u'26832': 5125,
 u'67579': 4500,
 u'67574': 2900,
 u'67571': 3525,
 u'103474': 2900,
 u'68634': 1995,
 u'96980': 2350,
 u'68630': 1600,
 u'68631': 1950,
 u'96985': 2495,
 u'96984': 3450,
 u'96989': 3895,
 u'68638': 2200,
 u'106482': 2495,
 u'106480': 2650,
 u'110552': 9870,
 u'54035': 5000,
 u'54034': 1800,
 u'106621': 2650,
 u'24579': 6800,
 u'24578': 3199,
 u'24577': 3200,
 u'24576': 2675,
 u'24572': 2350,
 u'24571': 3100,
 u'79724': 3975,
 u'58558': 2395,
 u'58559': 1455,
 u'79720': 1500,
 u'91452': 8000,
 u'62121': 1950,
 u'28402': 2100,
 u'28401': 2800,
 u'91458': 2200,
 u'58557': 2600,
 u'28405': 3610,
 u'28404': 2150,
 u'115072': 4065,
 u'115074': 2500,
 u'95820': 3095,
 u'34327': 2750,
 u'34325': 3950,
 u'115079': 3550,
 u'34321': 1875,
 u'118801': 4175,
 u'92830': 2700,
 u'35057': 2675,
 u'86709': 2200,
 u'35055': 2795,
 u'35052': 6500,
 u'35053': 16500,
 u'35051': 2895,
 u'102716': 3295,
 u'73516': 3200,
 u'109287': 5000,
 u'91982': 1725,
 u'91980': 2840,
 u'91981': 3100,
 u'91986': 2300,
 u'91985': 3125,
 u'55121': 2580,
 u'55125': 2050,
 u'55127': 2100,
 u'118707': 12600,
 u'112047': 5000,
 u'118704': 3323,
 u'110516': 4900,
 u'110517': 7980,
 u'110515': 2800,
 u'23718': 2300,
 u'23719': 4050,
 u'23717': 4950,
 u'93582': 2700,
 u'90924': 4050,
 u'93585': 3400,
 u'93587': 1575,
 u'59204': 6195,
 u'59207': 1950,
 u'59201': 7000,
 u'27008': 3970,
 u'59202': 3250,
 u'27007': 2250,
 u'27002': 3495,
 u'59208': 4295,
 u'92187': 2800,
 u'73600': 4300,
 u'73603': 2700,
 u'73602': 5100,
 u'73605': 2800,
 u'73607': 2500,
 u'109282': 4450,
 u'74051': 3475,
 u'74053': 3300,
 u'74055': 6075,
 u'74054': 3300,
 u'74056': 3495,
 u'74058': 1600,
 u'69076': 4400,
 u'32589': 1850,
 u'32588': 3121,
 u'78928': 5500,
 u'55784': 2000,
 u'55786': 2600,
 u'55787': 5600,
 u'32585': 1785,
 u'55781': 2500,
 u'32587': 2295,
 u'98600': 1600,
 u'98601': 6495,
 u'98606': 14395,
 u'98604': 4200,
 u'115929': 3675,
 u'66787': 5995,
 u'97630': 2800,
 u'121823': 10500,
 u'9943': 2995,
 u'9940': 1450,
 u'56478': 1300,
 u'9946': 2300,
 u'9947': 14800,
 u'35582': 3600,
 u'9945': 5000,
 u'56473': 2675,
 u'107917': 1995,
 u'9948': 2975,
 u'56470': 1995,
 u'107911': 2400,
 u'57788': 1825,
 u'32054': 2895,
 u'57783': 2000,
 u'57780': 2600,
 u'57781': 3200,
 u'57787': 2900,
 u'69036': 4300,
 u'32058': 2500,
 u'55872': 2895,
 u'52789': 4450,
 u'55870': 1550,
 u'55871': 3500,
 u'55874': 2850,
 u'56789': 2995,
 u'56788': 2300,
 u'25714': 2725,
 u'25715': 2755,
 u'69134': 4200,
 u'25710': 3350,
 u'25712': 5700,
 u'25718': 2650,
 u'62925': 7050,
 u'52781': 5415,
 u'21879': 2350,
 u'104754': 7350,
 u'104757': 4695,
 u'122736': 2795,
 u'100808': 3940,
 u'26066': 2295,
 u'26065': 3300,
 u'26062': 3295,
 u'26061': 2550,
 u'26069': 3600,
 u'64942': 3200,
 u'64941': 5225,
 u'64946': 2500,
 u'64944': 3895,
 u'95558': 2400,
 u'99388': 3595,
 u'75096': 1795,
 u'75097': 4772,
 u'75093': 3095,
 u'75090': 2100,
 u'75091': 3000,
 u'100805': 2030,
 u'81977': 2700,
 u'101986': 2350,
 u'57432': 1550,
 u'44424': 2000,
 u'101982': 4000,
 u'53954': 7060,
 u'36776': 3750,
 u'57439': 1920,
 u'36775': 2700,
 u'36772': 3675,
 u'101989': 3000,
 u'40963': 2900,
 u'58963': 6000,
 u'14669': 6495,
 u'105404': 5500,
 u'58960': 2275,
 u'105402': 4337,
 u'58966': 4600,
 u'33728': 3350,
 u'33729': 4625,
 u'14662': 2810,
 u'33725': 2975,
 u'14665': 6190,
 u'18565': 8995,
 u'33721': 3704,
 u'106663': 10000,
 u'106662': 5450,
 u'106661': 3130,
 u'106660': 6900,
 u'106667': 3000,
 u'106665': 2500,
 u'106664': 2500,
 u'38600': 6250,
 u'38601': 2350,
 u'38606': 1549,
 u'102752': 2400,
 u'83432': 1795,
 u'102757': 3500,
 u'83434': 2950,
 ...}

In [5]:
import pandas as pd

In [6]:
p = pd.Series(d['price'], name='price')

In [7]:
L = pd.Series(d['listing_id'], name='ID')

In [8]:
pd.concat([p, L], axis=1)

        price       ID
10       3000  7211212
10000    5465  7150865
100004   2850  6887163
100007   3275  6888711
100013   3350  6934781
100014   7995  6894514
100016   3600  6930771
100020   5645  6867392
100026   1725  6898799
100027   5800  6814332
100030   1950  6869199
10004    1675  7102986
100044   3000  6895442
100048   6895  6846213
10005    3050  7089402
100051   2350  6889043
100052   3650  6913348
100053   1695  6894111
100055   5000  6900220
100058   3973  6848536
100062   4395  6858062
100063   2999  6836760
100065   2595  6866830
100066   3695  6885927
10007    7400  7120132
100071   7500  6933499
100075   2295  6921632
100076   3164  6913084
100079   1350  6907079
100081   5600  6925264
...       ...      ...
99915    3126  6921019
99917    3325  6926146
99919    2100  6844805
99921    3500  6943991
99923   11950  6822618
99924    2980  6918969
99931    2850  6921162
99933    2885  6819357
99935    2950  6893263
99937    2650  6873182
9994     4850  7114685
99953    3475  6924210
99956    5815  6884807
99960    2050  6825168
99961    4600  6911061
99964    2000  6942494
99965    9200  6819478
99966    4550  6878391
99979    1900  6871559
99980    2500  6933865
99982    2500  6837242
99984    2675  6815109
99986    3645  6871681
99987    2179  6856001
99988    4500  6913833
9999     3200  7098690
99991    3950  6822449
99992    2595  6881461
99993    3350  6841891
99994    2200  6858245

[49352 rows x 2 columns]

In [9]:
s2 = pd.Series(d['interest_level'], name='interest')
s3 = pd.Series(d['display_address'], name='address')
s4 = pd.Series(d['description'], name='description')
s5 = pd.Series(d['created'], name='created')
s6 = pd.Series(d['bedrooms'], name='bed')
s7 = pd.Series(d['longitude'], name='longitude')
s8 = pd.Series(d['photos'], name='photos')
s9 = pd.Series(d['manager_id'], name='manager_id')
s10 = pd.Series(d['latitude'], name='latitude')
s11 = pd.Series(d['bathrooms'], name='bathrooms')
s12 = pd.Series(d['building_id'], name='building_id')
s13 = pd.Series(d['street_address'], name='street_address')
s14 = pd.Series(d['features'], name='features')

In [10]:
def dict_to_pd_frame(d,cols):
    result=[]
    for col in cols:
        result.append(pd.Series(d[col],name=col))
    return pd.concat(result, axis=1)

df=dict_to_pd_frame(d,d.keys())

In [11]:
df

,listing_id,interest_level,display_address,description,created,price,bedrooms,longitude,photos,manager_id,latitude,bathrooms,building_id,street_address,features
10,7211212,medium,Metropolitan Avenue,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,2016-06-24 07:54:24,3000,3,-73.9425,[https://photos.renthop.com/2/7211212_1ed4542e...,5ba989232d0489da1b5f2c45f6688adc,40.7145,1.5,53a5b119ba8f7b61d4e010512e0dfc85,792 Metropolitan Avenue,[]
10000,7150865,low,Columbus Avenue,,2016-06-12 12:19:27,5465,2,-73.9667,[https://photos.renthop.com/2/7150865_be3306c5...,7533621a882f71e25173b27e3139d83d,40.7947,1.0,c5c8a357cba207596b04d1afd1e4f130,808 Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow..."
100004,6887163,high,W 13 Street,"Top Top West Village location, beautiful Pre-w...",2016-04-17 03:26:41,2850,1,-74.0018,[https://photos.renthop.com/2/6887163_de85c427...,d9039c43983f6e564b1482b273bd7b01,40.7388,1.0,c3ba40552e2120b0acfc3cb5730bb2aa,241 W 13 Street,"[Laundry In Building, Dishwasher, Hardwood Flo..."
100007,6888711,low,East 49th Street,Building Amenities - Garage - Garden - fitness...,2016-04-18 02:22:02,3275,1,-73.9677,[https://photos.renthop.com/2/6888711_6e660cee...,1067e078446a7897d2da493d2f741316,40.7539,1.0,28d9ad350afeaab8027513a3e52ac8d5,333 East 49th Street,"[Hardwood Floors, No Fee]"
100013,6934781,low,West 143rd Street,Beautifully renovated 3 bedroom flex 4 bedroom...,2016-04-28 01:32:41,3350,4,-73.9493,[https://photos.renthop.com/2/6934781_1fa4b41a...,98e13ad4b495b9613cef886d79a6291f,40.8241,1.0,0,500 West 143rd Street,[Pre-War]
100014,6894514,medium,West 18th Street,,2016-04-19 04:24:47,7995,4,-74.0028,[https://photos.renthop.com/2/6894514_9abb8592...,b209e2c4384a64cc307c26759ee0c651,40.7429,2.0,38a913e46c94a7f46ddf19b756a9640c,350 West 18th Street,[]
100016,6930771,low,West 107th Street,Stunning unit with a great location and lots o...,2016-04-27 03:19:56,3600,2,-73.9660,[https://photos.renthop.com/2/6930771_7e3622b6...,01287194f20de51872e81f660def4784,40.8012,1.0,3ba49a93260ca5df92fde024cb4ca61f,210 West 107th Street,"[prewar, elevator, Dogs Allowed, Cats Allowed,..."
100020,6867392,low,West 21st Street,"This huge sunny ,plenty of lights 1 bed/2 bath...",2016-04-13 06:01:42,5645,1,-73.9957,[https://photos.renthop.com/2/6867392_b18283f6...,e6472c7237327dd3903b3d6f6a94515a,40.7427,2.0,0372927bcb6a0949613ef5bf893bbac7,155 West 21st Street,"[Doorman, Elevator, Pre-War, Terrace, Laundry ..."
100026,6898799,medium,Hamilton Terrace,<p><a website_redacted,2016-04-20 02:36:35,1725,1,-73.9457,[https://photos.renthop.com/2/6898799_3759be4c...,c1a6598437b7db560cde66e5a297a53f,40.8234,1.0,a7efbeb58190aa267b4a9121cd0c88c0,63 Hamilton Terrace,"[Cats Allowed, Dogs Allowed, Elevator, Laundry..."
100027,6814332,low,522 E 11th,This is a spacious four bedroom with every bed...,2016-04-02 02:58:15,5800,4,-73.9808,[https://photos.renthop.com/2/6814332_e19a8552...,23a01ea7717b38875f5b070282d1b9d2,40.7278,2.0,0,522 E 11th,"[Dishwasher, Hardwood Floors]"
100030,6869199,low,York Avenue,New to the market! Spacious studio located in ...,2016-04-14 01:10:30,1950,0,-73.9467,[https://photos.renthop.com/2/6869199_06b2601f...,e32475a6134d6d18279946b7b20a0f12,40.7769,1.0,0,1661 York Avenue,[]
10004,7102986,low,W. 173rd Street,Check out this one bedroom apartment in a grea...,2016-06-03 03:21:22,1675,1,-73.9396,[https://photos.renthop.com/2/7102986_ca6af538...,2dee0868ac01057760055b856e66e942,40.8448,1.0,0,644 W. 173rd Street,"[prewar, dishwasher, HIGHRISE, ROOFDECK, EAT I..."
100044,6895442,high,E 38th St,***LOW FEE. Beautiful CHERRY OAK WOODEN FLOORS...,2016-04-19 05:37:25,3000,2,-73.9770,[https://photos.renthop.com/2/6895442_34d617a5...,537e06890f6a86dbb70c187db5be4d55,40.7488,1.0,67c9b420da4a365bc26a6cd0ef4a5320,137 E 38th St,"[Doorman, Elevator, Laundry in Building, No Fee]"
100048,6846213,low,West 63rd Street,Lincoln Square's premier full service building...,2016-04-09 01:22:11,6895,2,-73.9817,[https://photos.renthop.com/2/6846213_83258754...,3813434aabfbad659a45f86a740cd23f,40.7707,2.0,0,30 West 63rd Street,"[Swimming Pool, Doorman, Fitness Center, No Fe..."
10005,7089402,low,East 56th St..,Spacious 1-Bedroom to fit King-sized bed comfo...,2016-06-01 03:11:01,3050,1,-73.9648,[https://photos.renthop.com/2/7089402_66038eaa...,75f38d077366d7964c2f3bb80c3e7b1d,40.7584,1.0,0,315 East 56th St..,"[Elevator, Multi-Level, Laundry in Building, D..."
100051,6889043,medium,East 34th Street,Stunning full renovated studio unit. High cei...,2016-04-18 02:36:00,2350,0,-73.9743,[https://photos.renthop.com/2/6889043_a3e1c004...,dbbb6b990661b1e507a387f019bcb1a0,40.7439,1.0,bfb9405149bfff42a92980b594c28234,340 East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in..."
100052,6913348,low,1st Ave.,East Village is a great community with great p...,2016-04-22 05:57:16,3650,2,-73.9830,[https://photos.renthop.com/2/6913348_829f19ac...,0411b25b134141100d8214ed6ec02f56,40.7305,1.0,642cc2c920512ffe2a74c28122f8b47f,214 1st Ave.,[Hardwood Floors]
100053,6894111,low,Thayer St,"*Location: Thayer St. &amp; Broadway, Manhatta...",2016-04-19 03:36:28,1695,1,-73.9280,[https://photos.renthop.com/2/6894111_571fa57d...,ab15d581a04ed87b6f25d5aff8ddde30,40.8643,1.0,0,98 Thayer St,"[prewar, LOWRISE, EAT IN KITCHEN, SIMPLEX, HAR..."
100055,6900220,low,West 106th Street,,2016-04-20 04:00:32,5000,4,-73.9638,[],8f5a9c893f6d602f4953fcc0b8e6e9b4,40.7999,1.0,cc4c6ae9225df6d2395c4e16c235f7ab,127 West 106th Street,"[No Fee, Cats Allowed, Dogs Allowed]"
100058,6848536,low,1st Avenue,,2016-04-09 03:49:42,3973,1,-73.9799,[https://photos.renthop.com/2/6848536_9a3e1f87...,8f5a9c893f6d602f4953fcc0b8e6e9b4,40.7328,1.0,dc3cae15729b48fec3394f9295671991,272 1st Avenue,"[Cats Allowed, Dogs Allowed]"
100062,6858062,low,Madison Avenue,BEAUTIFUL 2 BEDROOM POSSIBLE CONVERSION INTO T...,2016-04-12 02:39:45,4395,3,-73.9845,[https://photos.renthop.com/2/6858062_5cfb9d90...,3793e58c60343a3fd6846ca2d2ef3c7f,40.7454,1.0,205f95d4a78f1f3befda48b89edc9669,121 Madison Avenue,"[Doorman, Elevator, Dishwasher, Hardwood Floors]"
100063,6836760,medium,"E 30th St,",No fee huge two bedroom apartment. Great locat...,2016-04-07 02:11:45,2999,2,-73.9794,[https://photos.renthop.com/2/6836760_6edeb636...,e6472c7237327dd3903b3d6f6a94515a,40.7427,1.0,ecea86b79afa539505aa4bad3ff449c6,"210 E 30th St,","[Elevator, Central A/C, Walk in Closet(s), Par..."
100065,6866830,low,East 35th Street,,2016-04-13 05:17:43,2595,1,-73.9741,[],8f5a9c893f6d602f4953fcc0b8e6e9b4,40.7447,1.0,1a6cf9b71da65cdc0cfd5015a75317ac,326 East 35th Street,"[Cats Allowed, Dogs Allowed]"
100066,6885927,low,Liberty Street,CooperCooper.com :: Web ID #179546; Access 100...,2016-04-17 02:26:52,3695,1,-74.0081,[https://photos.renthop.com/2/6885927_3eb33bbc...,6e5c10246156ae5bdcd9b487ca99d96a,40.7074,1.0,a6200d7448037cfee809b2451219f879,10 Liberty Street,"[Doorman, Fitness Center, Pool, Elevator, Publ..."
10007,7120132,medium,W 18 St.,SPRAWLING 2 BEDROOM FOUND! ENJOY THE LUXURY OF...,2016-06-07 04:39:56,7400,4,-73.9936,[https://photos.renthop.com/2/7120132_8e47916c...,0cff4a2a147d81e51ae8a91289e129f7,40.7391,2.0,05b871a1e1e0368391160bcefc608e00,30 W 18 St.,"[Balcony, Doorman, Elevator, Fitness Center, T..."
100071,6933499,low,East 56th,Amazing 4 bedroom convertible. Remarkably luxu...,2016-04-27 06:43:40,7500,4,-73.9653,[https://photos.renthop.com/2/6933499_53ad35f0...,ad3d8ddc52c7e0859b5c6c7f7949c3bd,40.7584,3.5,45b4143a9841eb63d7203c4f21a64ff7,310 East 56th,"[Roof Deck, Dining Room, Balcony, Doorman, Ele..."
100075,6921632,medium,E 81st St.,Don't miss out on this fantastic apartment.......,2016-04-25 02:29:50,2295,1,-73.9502,[https://photos.renthop.com/2/6921632_563cdcee...,4f9b376a972b863bbfbdcdc8d717fa4e,40.7728,1.0,d68497ff1f5ac77f143e5f21817ed6fb,444 E 81st St.,"[Dishwasher, Hardwood Floors, No Fee]"
100076,6913084,low,West 57th Street,The TRUE 1 bedroom apartment features extra la...,2016-04-22 05:39:10,3164,1,-73.9917,[https://photos.renthop.com/2/6913084_e1aef7e1...,63e8c482071c22f43dd91b954e75cc2c,40.7709,1.0,ec447453d3b8033e14a7b54ba1e13e02,601 West 57th Street,"[Roof Deck, Doorman, Elevator, Laundry in Buil..."
100079,6907079,high,1215 Morris Avenue,"Currently under renovation, this one b...",2016-04-21 05:27:10,1350,1,-73.9141,[https://photos.renthop.com/2/6907079_2cc12101...,12c0a30e296faa0dfd422fe918d7d4f4,40.8335,1.0,f06ad2f6f1a821c8efc03dc195d369df,1215 Morris Avenue,[]
100081,6925264,low,E 79th St.,Gut Renovated Apartment with Stainless steel a...,2016-04-26 02:59:37,5600,2,-73.9506,[https://photos.renthop.com/2/6925264_59f5dc7a...,797f306f24780e1a24e4f063d46a2d8d,40.7716,2.0,f115a9bff3a9c4e6eedc9114374b3d74,435 E 79th St.,"[Doorman, Elevator, Fitness Center, Pre-War, L..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99915,6921019,low,North 10th Street,"Elegant, spacious one bedroom in modern luxury...",2016-04-25 01:13:37,3126,1,-73.9531,[https://photos.renthop.com/2/6921019_05091585...,ac8e91c7b3c57a65a05683e04e4ee334,40.7176,1.0,0,250 North 10th Street,"[Swimming Pool, Doorman, Fitness Center, Dogs ..."
99917,6926146,low,W 58th St,,2016-04-26 04:43:14,3325,1,-73.9785,[https://photos.renthop.com/2/6926146_f82d7aff...,b06e1df5b2aff97e494bf9aea0d3eb7d,40.7655,1.0,e243886a4cac69881c07c6a1f38185bf,150 W 58th St,"[Cats Allowed, Dogs Allowed, Doorman, Elevator..."
99919,6844805,medium,East 78th Street,(((((IMPORTANT NOTICE))))) If you are planning...,2016-04-08 05:51:57,2100,0,-73.9539,[https://photos.renthop.com/2/6844805_b2a3a213...,e6472c7237327dd3903b3d6f6a94515a,40.7721,1.0,da2f861e30b1391e8368438efddaa2a7,353 East 78th Street,"[Elevator, Laundry in Building, Laundry in Uni..."
99921,6943991,medium,Ridge Blvd.,WASHER & DRYER IN UNIT ++ 5 MINUTE WALK TO R T...,2016-04-29 15:03:29,3500,2,-74.0360,[https://photos.renthop.com/2/6943991_0a32ffd3...,d23f9a9e6b9f6003f26017bda6dd1cb2,40.6182,1.0,fc0676a4d4fdb4e767faf6414975a0cb,9319 Ridge Blvd,"[Furnished, Laundry In Unit]"
99923,6822618,low,West 81st Street,Tremendous Classic Six in a Luxurious Prewar D...,2016-04-05 01:12:45,11950,2,-73.9731,[https://photos.renthop.com/2/6822618_d04c2ece...,7dbded20b3fed08d7d100bf2214e624b,40.7829,2.0,0,25 West 81st Street,"[Doorman, Pre-War, Dogs Allowed, Cats Allowed]"
99924,6918969,low,8th Avenue,Luxury Living--- Full-Time Doorman--- Concierg...,2016-04-24 03:15:18,2980,1,-73.9847,[https://photos.renthop.com/2/6918969_e88539cc...,e1c98bf7f1a044ec4df76abee5f0f5e6,40.7637,1.0,93cd24891f8423d45ac587ab1fdb1225,888 8th Avenue,"[Doorman, Laundry in Building, Laundry in Unit..."
99931,6921162,low,Thompson Street,Only one block form Washington Square Park! Ne...,2016-04-25 01:20:23,2850,1,-73.9987,[https://photos.renthop.com/2/6921162_5d6df102...,6622a56323ab90abcace1f529cd7c95d,40.7293,1.0,0,230 Thompson Street,"[Dogs Allowed, Cats Allowed]"
99933,6819357,low,Water,THIS RESIDENCE FEATURES STAINLESS STEAL APPLI...,2016-04-03 03:51:21,2885,2,-74.0043,[https://photos.renthop.com/2/6819357_700208a6...,6f1aeac17da650a577a87ac3a143a5ec,40.7075,1.0,80a120d6bc3aba97f40fee8c2204524b,200 Water,"[Roof Deck, Dining Room, Doorman, Elevator, Fi..."
99935,6893263,low,East 12th Street,This newly renovated 1 bedroom unit is recentl...,2016-04-19 02:58:55,2950,1,-73.9808,[https://photos.renthop.com/2/6893263_f1f39ce2...,4d6dd180ce32ef726c992c6647981978,40.7287,1.0,0,508 East 12th Street,[]
99937,6873182,low,York Avenue,"Bedroom on top, Living room on bottom<br /><br...",2016-04-14 05:39:33,2650,0,-73.9467,[https://photos.renthop.com/2/6873182_babdece5...,d90f2151c55212a41a0d965198d5e555,40.7769,1.5,d48767c37a934daaf0bbb0e58c755d0c,1661 York Avenue,"[Pre-War, Laundry in Building, Dishwasher, Har..."
9994,7114685,low,West 98th Street,Don't miss out on this spacious and beautiful ...,2016-06-06 01:22:44,4850,2,-73.9705,[https://photos.renthop.com/2/7114685_7b7f598a...,001ce808ce1720e24a9510e014c69707,40.7957,1.0,0,220 West 98th Street,"[Doorman, Pre-War, Dogs Allowed, Cats Allowed]"
99953,6924210,low,West 58th Street,"This exquisitely appointed 1 bedroom, 1 bath r...",2016-04-26 02:18:16,3475,1,-73.9785,[https://photos.renthop.com/2/6924210_27c32e80...,5ce67c680fc5550aaa20b7c90380de4c,40.7655,1.0,e243886a4cac69881c07c6a1f38185bf,150 West 58th Street,"[Doorman, Elevator, Furnished, Pre-War, Dishwa..."
99956,6884807,low,Nassau Street,This spacious two bedroom apartment features e...,2016-04-16 16:39:50,5815,2,-74.0084,[https://photos.renthop.com/2/6884807_158a7214...,26d69329a0f3b9abecbddd6abcb5b622,40.7095,2.0,0,Nassau Street,"[Common Outdoor Space, Cats Allowed, Dogs Allo..."
99960,6825168,medium,Baxter Street,Great Lower East Side one bedroom.Well maintai...,2016-04-05 04:35:32,2050,1,-73.9989,[https://photos.renthop.com/2/6825168_f94cee7d...,453d46f8113e1f2c730c2ee5a4469c71,40.7179,1.0,6f1e2020bd0e4ff48d3a5d482944a753,119 Baxter Street,[Hardwood Floors]
99961,6911061,low,East 3rd Street,THIS LARGE AND SPACIOUS 3 BD/ONE BA APARTMENT ...,2016-04-22 03:11:44,4600,3,-73.9824,[https://photos.renthop.com/2/6911061_25c3f3b1...,1fb46c4a72bcf764ac35fc23f394760d,40.7222,2.0,ae3e5e3d93ea18140752078f9a3177af,222 East 3rd Street,"[Doorman, Elevator, Laundry in Building, Dishw..."
99964,6942494,medium,E 77 St,77TH ST! FULLY GUT RENOV STUDIO! HI CEIL! XPSD...,2016-04-29 05:20:49,2000,0,-73.9525,[https://photos.renthop.com/2/6942494_edcfce0d...,fd960446d2a41002d3b36f25740157ca,40.7708,1.0,f8009151babfad197b48f6922eec99f2,425 E 77 St,"[Loft, Multi-Level, Dishwasher, Hardwood Floors]"
99965,6819478,low,East 87th Street,Full-Time Doorman PET FRIENDLYElevator GYMLaun...,2016-04-03 05:23:23,9200,3,-73.9463,[https://photos.renthop.com/2/6819478_832d3d70...,2e67103872a6d3e53ccd4e6229bae9b1,40.7766,2.0,a485c2deb62ad3c9c76edebd532a446c,501 East 87th Street,"[Swimming Pool, Dining Room, Doorman, Elevator..."
99966,6878391,low,East 72nd Street,This is a Great Opportunity to Rent an Excelle...,2016-04-15 05:36:39,4550,3,-73.9603,[https://photos.renthop.com/2/6878391_59754267...,fa0e15022a76c748bbc5e1f420439921,40.7695,1.0,a36895b9975c6991ca0fa1d9a99023a1,200 East 72nd Street,"[Roof Deck, Doorman, Elevator, Fitness Center,..."
99979,6871559,low,Eldert St,,2016-04-14 03:32:24,1900,1,-73.9134,[],324631e1aacaa41bc4475f879756bbb6,40.6865,1.0,e4490b8e6a410d39d38e40e572243a64,51 eldert st,[]
99980,6933865,low,John Street,Incredibly sunny and spacious studio apartment...,2016-04-27 12:52:12,2500,0,-74.0105,[https://photos.renthop.com/2/6933865_9bdcae03...,045f9f5708f6896535892b85a81d8151,40.7090,1.0,d16f875956b264d5920d8424631091d4,116 John Street,"[Common Outdoor Space, Cats Allowed, Dogs Allo..."
99982,6837242,high,W 54 St.,"LUXURY BUILDING IN MIDTOWN WEST, 24 HR DOORMAN...",2016-04-07 02:29:00,2500,1,-73.9840,[https://photos.renthop.com/2/6837242_3fbdc629...,e6472c7237327dd3903b3d6f6a94515a,40.7645,1.0,6134e7c4dd1a98d9aee36623c9872b49,260 W 54 St.,"[Doorman, Elevator, Fitness Center, Laundry in..."
99984,6815109,low,E 76 Street,Huge true king size one bedroom in an elevator...,2016-04-02 03:17:03,2675,1,-73.9591,[https://photos.renthop.com/2/6815109_1ec75160...,ac888923cda3b9e4f0311267be25de9c,40.7728,1.0,8e7bd3cbdd67a0dcc719224a41699d2b,191 E 76 Street,"[Elevator, Multi-Level, Dishwasher, Hardwood F..."
99986,6871681,low,Charles Street,"Charming one bedroom! Hardwood floors, sunny, ...",2016-04-14 03:39:42,3645,1,-74.0007,[https://photos.renthop.com/2/6871681_f2e17c12...,f9920c687eb43480349a4a3e16fc39cf,40.7350,1.0,399f92c2a78ada2f01c8414ce3bc909b,6 Charles Street,"[Elevator, Hardwood Floors]"
99987,6856001,low,East 89th Street,**89th & Park Ave! (block from the central par...,2016-04-11 03:29:05,2179,1,-73.9719,[https://photos.renthop.com/2/6856001_5d031c59...,bf0d9091553cd99e68fe92b23966e140,40.7889,1.0,0,117 East 89th Street,[Dishwasher]
99988,6913833,medium,East 10th Street,24hr Doorman Luxury building in the heart of t...,2016-04-22 15:44:11,4500,1,-73.9869,[https://photos.renthop.com/2/6913833_a5587e14...,e9920062e07ee893c10e38d0259665b0,40.7296,1.0,3b13a6597596619bdbc8281096f21d23,166 2nd avenue,"[Cats Allowed, No Fee, Doorman, Elevator, Laun..."
9999,7098690,medium,E 30 St,"30TH/3RD, MASSIVE CONV 2BR IN LUXURY FULL SERV...",2016-06-02 05:41:05,3200,2,-73.9790,[https://photos.renthop.com/2/7098690_18396d32...,2a1ee03b449700c3a15dd8c9a505c525,40.7426,1.0,297160caf8a88c10718b492d4672c6b4,230 E 30 St,"[Elevator, Laundry in Building, Laundry in Uni..."
99991,6822449,low,Rector Pl,"HIGH END condo finishes, swimming pool, and ki...",2016-04-04 18:22:34,3950,1,-74.0163,[https://photos.renthop.com/2/6822449_b429587b...,ef20d40b528500037e37b167787ac089,40.7102,1.0,9e871ccfea7b07686c101548ca693af6,225 Rector Place,"[Common Outdoor Space, Cats Allowed, Dogs Allo..."
99992,6881461,low,West 45th Street,Large Renovated One Bedroom Apartment with Sta...,2016-04-16 02:13:40,2595,1,-73.9900,[https://photos.renthop.com/2/6881461_20a86530...,d889a9552265fe359e7d36d172084fcb,40.7601,1.0,7967a1280bf3f7644500fc79d2696b0e,341 West 45th Street,"[Doorman, Elevator, Pre-War, Dogs Allowed, Cat..."
99993,6841891,low,Wall Street,Stylishly sleek studio apartment with unsurpas...,2016-04-08 02:13:33,3350,0,-74.0101,[https://photos.renthop.com/2/6841891_124c9c44...,9fd3af5b2d23951e028059e8940a55d7,40.7066,1.0,ad67f6181a49bde19218929b401b31b7,37 Wall Street,"[Doorman, Elevator, Pre-War, Dogs Allowed, Cat..."
99994,6858245,low,Park Terrace East,Look no further!!! This giant 2 bedroom apart...,2016-04-12 02:48:07,2200,2,-73.9172,[https://photos.renthop.com/2/6858245_c4380bde...,d7f57128272bfd82e33a61999b5f4c42,40.8699,1.0,5173052db6efc0caaa4d817112a70f32,30 Park Terrace East,[Hardwood Floors]

In [12]:
s8

10        [https://photos.renthop.com/2/7211212_1ed4542e...
10000     [https://photos.renthop.com/2/7150865_be3306c5...
100004    [https://photos.renthop.com/2/6887163_de85c427...
100007    [https://photos.renthop.com/2/6888711_6e660cee...
100013    [https://photos.renthop.com/2/6934781_1fa4b41a...
100014    [https://photos.renthop.com/2/6894514_9abb8592...
100016    [https://photos.renthop.com/2/6930771_7e3622b6...
100020    [https://photos.renthop.com/2/6867392_b18283f6...
100026    [https://photos.renthop.com/2/6898799_3759be4c...
100027    [https://photos.renthop.com/2/6814332_e19a8552...
100030    [https://photos.renthop.com/2/6869199_06b2601f...
10004     [https://photos.renthop.com/2/7102986_ca6af538...
100044    [https://photos.renthop.com/2/6895442_34d617a5...
100048    [https://photos.renthop.com/2/6846213_83258754...
10005     [https://photos.renthop.com/2/7089402_66038eaa...
100051    [https://photos.renthop.com/2/6889043_a3e1c004...
100052    [https://photos.renthop.com/2/6913348_829f19ac...
100053    [https://photos.renthop.com/2/6894111_571fa57d...
100055                                                   []
100058    [https://photos.renthop.com/2/6848536_9a3e1f87...
100062    [https://photos.renthop.com/2/6858062_5cfb9d90...
100063    [https://photos.renthop.com/2/6836760_6edeb636...
100065                                                   []
100066    [https://photos.renthop.com/2/6885927_3eb33bbc...
10007     [https://photos.renthop.com/2/7120132_8e47916c...
100071    [https://photos.renthop.com/2/6933499_53ad35f0...
100075    [https://photos.renthop.com/2/6921632_563cdcee...
100076    [https://photos.renthop.com/2/6913084_e1aef7e1...
100079    [https://photos.renthop.com/2/6907079_2cc12101...
100081    [https://photos.renthop.com/2/6925264_59f5dc7a...
                                ...
99915     [https://photos.renthop.com/2/6921019_05091585...
99917     [https://photos.renthop.com/2/6926146_f82d7aff...
99919     [https://photos.renthop.com/2/6844805_b2a3a213...
99921     [https://photos.renthop.com/2/6943991_0a32ffd3...
99923     [https://photos.renthop.com/2/6822618_d04c2ece...
99924     [https://photos.renthop.com/2/6918969_e88539cc...
99931     [https://photos.renthop.com/2/6921162_5d6df102...
99933     [https://photos.renthop.com/2/6819357_700208a6...
99935     [https://photos.renthop.com/2/6893263_f1f39ce2...
99937     [https://photos.renthop.com/2/6873182_babdece5...
9994      [https://photos.renthop.com/2/7114685_7b7f598a...
99953     [https://photos.renthop.com/2/6924210_27c32e80...
99956     [https://photos.renthop.com/2/6884807_158a7214...
99960     [https://photos.renthop.com/2/6825168_f94cee7d...
99961     [https://photos.renthop.com/2/6911061_25c3f3b1...
99964     [https://photos.renthop.com/2/6942494_edcfce0d...
99965     [https://photos.renthop.com/2/6819478_832d3d70...
99966     [https://photos.renthop.com/2/6878391_59754267...
99979                                                    []
99980     [https://photos.renthop.com/2/6933865_9bdcae03...
99982     [https://photos.renthop.com/2/6837242_3fbdc629...
99984     [https://photos.renthop.com/2/6815109_1ec75160...
99986     [https://photos.renthop.com/2/6871681_f2e17c12...
99987     [https://photos.renthop.com/2/6856001_5d031c59...
99988     [https://photos.renthop.com/2/6913833_a5587e14...
9999      [https://photos.renthop.com/2/7098690_18396d32...
99991     [https://photos.renthop.com/2/6822449_b429587b...
99992     [https://photos.renthop.com/2/6881461_20a86530...
99993     [https://photos.renthop.com/2/6841891_124c9c44...
99994     [https://photos.renthop.com/2/6858245_c4380bde...
Name: photos, dtype: object

In [13]:
s8[0]

[u'https://photos.renthop.com/2/7211212_1ed4542ec81621d70d1061aa833e669c.jpg',
 u'https://photos.renthop.com/2/7211212_7dfc41dced69245065df83d08eed4a00.jpg',
 u'https://photos.renthop.com/2/7211212_c17853c4b869af6f53af08b0f5820b4c.jpg',
 u'https://photos.renthop.com/2/7211212_787ad8ea0c089792e7453e2121f8ac89.jpg',
 u'https://photos.renthop.com/2/7211212_2e88b0d293ee333c804c2f00536eee49.jpg']

In [14]:
len(s8[0])

5

In [15]:
s8.apply(len)

10         5
10000     11
100004     8
100007     3
100013     3
100014     5
100016    10
100020     5
100026     5
100027     9
100030     1
10004      5
100044     4
100048     6
10005      6
100051     2
100052     5
100053     8
100055     0
100058    32
100062     6
100063     5
100065     0
100066     4
10007      6
100071     7
100075     6
100076     6
100079     1
100081     1
          ..
99915      6
99917      9
99919      4
99921      6
99923      2
99924      3
99931      3
99933      4
99935      4
99937      7
9994       8
99953      1
99956      8
99960      3
99961      8
99964      3
99965      4
99966      4
99979      0
99980      4
99982      3
99984      4
99986      5
99987      8
99988      8
9999       4
99991      8
99992      3
99993      9
99994      7
Name: photos, dtype: int64

In [16]:
df.head(5)

,listing_id,interest_level,display_address,description,created,price,bedrooms,longitude,photos,manager_id,latitude,bathrooms,building_id,street_address,features
10,7211212,medium,Metropolitan Avenue,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,2016-06-24 07:54:24,3000,3,-73.9425,[https://photos.renthop.com/2/7211212_1ed4542e...,5ba989232d0489da1b5f2c45f6688adc,40.7145,1.5,53a5b119ba8f7b61d4e010512e0dfc85,792 Metropolitan Avenue,[]
10000,7150865,low,Columbus Avenue,,2016-06-12 12:19:27,5465,2,-73.9667,[https://photos.renthop.com/2/7150865_be3306c5...,7533621a882f71e25173b27e3139d83d,40.7947,1.0,c5c8a357cba207596b04d1afd1e4f130,808 Columbus Avenue,"[Doorman, Elevator, Fitness Center, Cats Allow..."
100004,6887163,high,W 13 Street,"Top Top West Village location, beautiful Pre-w...",2016-04-17 03:26:41,2850,1,-74.0018,[https://photos.renthop.com/2/6887163_de85c427...,d9039c43983f6e564b1482b273bd7b01,40.7388,1.0,c3ba40552e2120b0acfc3cb5730bb2aa,241 W 13 Street,"[Laundry In Building, Dishwasher, Hardwood Flo..."
100007,6888711,low,East 49th Street,Building Amenities - Garage - Garden - fitness...,2016-04-18 02:22:02,3275,1,-73.9677,[https://photos.renthop.com/2/6888711_6e660cee...,1067e078446a7897d2da493d2f741316,40.7539,1.0,28d9ad350afeaab8027513a3e52ac8d5,333 East 49th Street,"[Hardwood Floors, No Fee]"
100013,6934781,low,West 143rd Street,Beautifully renovated 3 bedroom flex 4 bedroom...,2016-04-28 01:32:41,3350,4,-73.9493,[https://photos.renthop.com/2/6934781_1fa4b41a...,98e13ad4b495b9613cef886d79a6291f,40.8241,1.0,0,500 West 143rd Street,[Pre-War]

In [17]:
feature_cols=['price','bedrooms','bathrooms']
new_df=df[feature_cols]

label_df=df['interest_level']

In [18]:
new_df.head(5)

        price  bedrooms  bathrooms
10       3000         3        1.5
10000    5465         2        1.0
100004   2850         1        1.0
100007   3275         1        1.0
100013   3350         4        1.0

In [19]:
label_df.head(5)

10        medium
10000        low
100004      high
100007       low
100013       low
Name: interest_level, dtype: object

NameError: name 'make_blobs' is not defined

In [21]:
import matplotlib.pyplot as plt

import numpy as np

from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import log_loss

np.random.seed(0)

# Generate data
X, y = new_df, label_df
m,n=new_df.shape
m1=int(m*0.6)
m2=int(m*0.8)

X_train, y_train = X[:m1], y[:m1]
X_valid, y_valid = X[m1:m2], y[m1:m2]
X_train_valid, y_train_valid = X[:m2], y[:m2]
X_test, y_test = X[m2:], y[m2:]

# Train uncalibrated random forest classifier on whole train and validation
# data and evaluate on test data
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train_valid, y_train_valid)
clf_probs = clf.predict_proba(X_test)
score = log_loss(y_test, clf_probs)

# Train random forest classifier, calibrate on validation data and evaluate
# on test data
clf = RandomForestClassifier(n_estimators=25)
clf.fit(X_train, y_train)
clf_probs = clf.predict_proba(X_test)
sig_clf = CalibratedClassifierCV(clf, method="sigmoid", cv="prefit")
sig_clf.fit(X_valid, y_valid)
sig_clf_probs = sig_clf.predict_proba(X_test)
sig_score = log_loss(y_test, sig_clf_probs)






print("Log-loss of")
print(" * uncalibrated classifier trained on 800 datapoints: %.3f "
      % score)
print(" * classifier trained on 600 datapoints and calibrated on "
      "200 datapoint: %.3f" % sig_score)


# generate grid over 2-simplex
p1d = np.linspace(0, 1, 20)
p0, p1 = np.meshgrid(p1d, p1d)
p2 = 1 - p0 - p1
p = np.c_[p0.ravel(), p1.ravel(), p2.ravel()]
p = p[p[:, 2] >= 0]

calibrated_classifier = sig_clf.calibrated_classifiers_[0]
prediction = np.vstack([calibrator.predict(this_p)
                        for calibrator, this_p in
                        zip(calibrated_classifier.calibrators_, p.T)]).T
prediction /= prediction.sum(axis=1)[:, None]

Log-loss of
 * uncalibrated classifier trained on 800 datapoints: 1.462
 * classifier trained on 600 datapoints and calibrated on 200 datapoint: 0.739

In [22]:
X.shape

(49352, 3)

In [23]:
y

10        medium
10000        low
100004      high
100007       low
100013       low
100014    medium
100016       low
100020       low
100026    medium
100027       low
100030       low
10004        low
100044      high
100048       low
10005        low
100051    medium
100052       low
100053       low
100055       low
100058       low
100062       low
100063    medium
100065       low
100066       low
10007     medium
100071       low
100075    medium
100076       low
100079      high
100081       low
           ...
99915        low
99917        low
99919     medium
99921     medium
99923        low
99924        low
99931        low
99933        low
99935        low
99937        low
9994         low
99953        low
99956        low
99960     medium
99961        low
99964     medium
99965        low
99966        low
99979        low
99980        low
99982       high
99984        low
99986        low
99987        low
99988     medium
9999      medium
99991        low
99992        low
99993        low
99994        low
Name: interest_level, dtype: object

In [24]:
import json

with open('test.json') as json_data:
    test_json = json.load(json_data)

In [25]:

test_df=dict_to_pd_frame(test_json,test_json.keys())

In [26]:
feature_cols=['price','bedrooms','bathrooms']
new_test_df=test_df[feature_cols]

In [27]:
new_test_df.head(5)

        price  bedrooms  bathrooms
0        2950         1        1.0
1        2850         2        1.0
100      3758         1        1.0
1000     3300         2        1.0
100000   4900         2        2.0

In [28]:
final_prob = sig_clf.predict_proba(new_test_df)

In [29]:
final_prob

array([[ 0.06009317,  0.74920937,  0.19069746],
       [ 0.09926586,  0.59292867,  0.30780547],
       [ 0.04219204,  0.8277893 ,  0.13001866],
       ...,
       [ 0.0897032 ,  0.70950064,  0.20079616],
       [ 0.06856111,  0.71790192,  0.21353697],
       [ 0.09926586,  0.59292867,  0.30780547]])

In [48]:
answer_df=pd.DataFrame(final_prob, columns=clf.classes_)

In [49]:
answer_df

           high       low    medium
0      0.060093  0.749209  0.190697
1      0.099266  0.592929  0.307805
2      0.042192  0.827789  0.130019
3      0.063363  0.663633  0.273003
4      0.043086  0.761019  0.195895
5      0.042736  0.784087  0.173177
6      0.085499  0.604272  0.310229
7      0.130203  0.578778  0.291020
8      0.108394  0.599053  0.292554
9      0.082117  0.668561  0.249323
10     0.042192  0.827789  0.130019
11     0.089703  0.709501  0.200796
12     0.043937  0.710958  0.245105
13     0.072785  0.759728  0.167487
14     0.132364  0.598972  0.268665
15     0.042662  0.789273  0.168064
16     0.049924  0.728797  0.221278
17     0.042192  0.827789  0.130019
18     0.045191  0.642410  0.312398
19     0.070551  0.663348  0.266101
20     0.066509  0.655111  0.278380
21     0.077149  0.679612  0.243239
22     0.042192  0.827789  0.130019
23     0.060497  0.577053  0.362450
24     0.042850  0.776294  0.180855
25     0.172666  0.564750  0.262585
26     0.042693  0.787098  0.170209
27     0.438992  0.360325  0.200683
28     0.045471  0.627217  0.327312
29     0.438992  0.360325  0.200683
...         ...       ...       ...
74629  0.061025  0.655681  0.283295
74630  0.204080  0.485256  0.310664
74631  0.062508  0.646615  0.290878
74632  0.049274  0.721905  0.228821
74633  0.061328  0.704990  0.233682
74634  0.060991  0.767587  0.171422
74635  0.042192  0.827789  0.130019
74636  0.042337  0.814559  0.143104
74637  0.042389  0.810163  0.147449
74638  0.069903  0.675642  0.254456
74639  0.042192  0.827789  0.130019
74640  0.042192  0.827789  0.130019
74641  0.042256  0.821733  0.136012
74642  0.063191  0.667404  0.269405
74643  0.146718  0.643942  0.209340
74644  0.042276  0.819870  0.137854
74645  0.124697  0.658169  0.217134
74646  0.048181  0.761177  0.190642
74647  0.058862  0.706088  0.235050
74648  0.044728  0.667501  0.287771
74649  0.081080  0.599363  0.319557
74650  0.108394  0.599053  0.292554
74651  0.043080  0.761424  0.195496
74652  0.142797  0.582721  0.274482
74653  0.042380  0.810887  0.146733
74654  0.121062  0.550736  0.328202
74655  0.042515  0.800176  0.157309
74656  0.089703  0.709501  0.200796
74657  0.068561  0.717902  0.213537
74658  0.099266  0.592929  0.307805

[74659 rows x 3 columns]

In [37]:
lisId=test_df['listing_id'].reset_index()
lisId

        index  listing_id
0           0     7142618
1           1     7210040
2         100     7103890
3        1000     7143442
4      100000     6860601
5      100001     6840081
6      100002     6922337
7      100003     6913616
8      100005     6937820
9      100006     6893933
10     100008     6832604
11     100009     6915282
12      10001     7127565
13     100010     6827899
14     100011     6934855
15     100012     6861826
16     100015     6871643
17     100017     6842542
18     100018     6934145
19     100019     6829365
20      10002     7167858
21     100021     6859483
22     100022     6861377
23     100023     6848960
24     100024     6918850
25     100025     6916867
26     100028     6895840
27     100029     6813539
28      10003     7116900
29     100031     6890328
...       ...         ...
74629   99957     6855560
74630   99958     6816731
74631   99959     6925764
74632    9996     7139280
74633   99962     6913068
74634   99963     6828445
74635   99967     6867865
74636   99968     6820397
74637   99969     6852197
74638    9997     7122934
74639   99970     6907838
74640   99971     6865896
74641   99972     6840250
74642   99973     6926011
74643   99974     6893100
74644   99975     6867538
74645   99976     6884360
74646   99977     6903964
74647   99978     6907851
74648    9998     7211166
74649   99981     6844290
74650   99983     6947597
74651   99985     6895423
74652   99989     6812077
74653   99990     6903956
74654   99995     6881005
74655   99996     6835379
74656   99997     6882352
74657   99998     6884758
74658   99999     6924212

[74659 rows x 2 columns]

In [51]:
df1=pd.concat([answer_df, lisId], axis=1)

In [52]:
cols=['listing_id','high','medium','low']

In [53]:
df2=df1[cols]
df2

       listing_id      high    medium       low
0         7142618  0.060093  0.190697  0.749209
1         7210040  0.099266  0.307805  0.592929
2         7103890  0.042192  0.130019  0.827789
3         7143442  0.063363  0.273003  0.663633
4         6860601  0.043086  0.195895  0.761019
5         6840081  0.042736  0.173177  0.784087
6         6922337  0.085499  0.310229  0.604272
7         6913616  0.130203  0.291020  0.578778
8         6937820  0.108394  0.292554  0.599053
9         6893933  0.082117  0.249323  0.668561
10        6832604  0.042192  0.130019  0.827789
11        6915282  0.089703  0.200796  0.709501
12        7127565  0.043937  0.245105  0.710958
13        6827899  0.072785  0.167487  0.759728
14        6934855  0.132364  0.268665  0.598972
15        6861826  0.042662  0.168064  0.789273
16        6871643  0.049924  0.221278  0.728797
17        6842542  0.042192  0.130019  0.827789
18        6934145  0.045191  0.312398  0.642410
19        6829365  0.070551  0.266101  0.663348
20        7167858  0.066509  0.278380  0.655111
21        6859483  0.077149  0.243239  0.679612
22        6861377  0.042192  0.130019  0.827789
23        6848960  0.060497  0.362450  0.577053
24        6918850  0.042850  0.180855  0.776294
25        6916867  0.172666  0.262585  0.564750
26        6895840  0.042693  0.170209  0.787098
27        6813539  0.438992  0.200683  0.360325
28        7116900  0.045471  0.327312  0.627217
29        6890328  0.438992  0.200683  0.360325
...           ...       ...       ...       ...
74629     6855560  0.061025  0.283295  0.655681
74630     6816731  0.204080  0.310664  0.485256
74631     6925764  0.062508  0.290878  0.646615
74632     7139280  0.049274  0.228821  0.721905
74633     6913068  0.061328  0.233682  0.704990
74634     6828445  0.060991  0.171422  0.767587
74635     6867865  0.042192  0.130019  0.827789
74636     6820397  0.042337  0.143104  0.814559
74637     6852197  0.042389  0.147449  0.810163
74638     7122934  0.069903  0.254456  0.675642
74639     6907838  0.042192  0.130019  0.827789
74640     6865896  0.042192  0.130019  0.827789
74641     6840250  0.042256  0.136012  0.821733
74642     6926011  0.063191  0.269405  0.667404
74643     6893100  0.146718  0.209340  0.643942
74644     6867538  0.042276  0.137854  0.819870
74645     6884360  0.124697  0.217134  0.658169
74646     6903964  0.048181  0.190642  0.761177
74647     6907851  0.058862  0.235050  0.706088
74648     7211166  0.044728  0.287771  0.667501
74649     6844290  0.081080  0.319557  0.599363
74650     6947597  0.108394  0.292554  0.599053
74651     6895423  0.043080  0.195496  0.761424
74652     6812077  0.142797  0.274482  0.582721
74653     6903956  0.042380  0.146733  0.810887
74654     6881005  0.121062  0.328202  0.550736
74655     6835379  0.042515  0.157309  0.800176
74656     6882352  0.089703  0.200796  0.709501
74657     6884758  0.068561  0.213537  0.717902
74658     6924212  0.099266  0.307805  0.592929

[74659 rows x 4 columns]

In [54]:
df2.to_csv('first_answer_file.csv', index=False)

In [33]:
test_df.head(5)

,listing_id,display_address,description,created,price,bedrooms,longitude,photos,manager_id,latitude,bathrooms,building_id,street_address,features
0,7142618,Suffolk Street,Large with awesome terrace--accessible via bed...,2016-06-11 05:29:41,2950,1,-73.9865,[https://photos.renthop.com/2/7142618_1c45a2c8...,b1b1852c416d78d7765d746cb1b8921f,40.7185,1.0,79780be1514f645d7e6be99a3de696c5,99 Suffolk Street,"[Elevator, Laundry in Building, Laundry in Uni..."
1,7210040,Thompson Street,Prime Soho - between Bleecker and Houston - Ne...,2016-06-24 06:36:34,2850,2,-74.0000,[https://photos.renthop.com/2/7210040_d824cc71...,d0b5648017832b2427eeb9956d966a14,40.7278,1.0,0,176 Thompson Street,"[Pre-War, Dogs Allowed, Cats Allowed]"
100,7103890,101 East 10th Street,New York chic has reached a new level ...,2016-06-03 04:29:40,3758,1,-73.9890,[https://photos.renthop.com/2/7103890_85b33077...,9ca6f3baa475c37a3b3521a394d65467,40.7306,1.0,3dbbb69fd52e0d25131aa1cd459c87eb,101 East 10th Street,"[Doorman, Elevator, No Fee]"
1000,7143442,South Third Street\r,Step into this fantastic new Construction in t...,2016-06-11 06:17:35,3300,2,-73.9571,[https://photos.renthop.com/2/7143442_0879e9e0...,0b9d5db96db8472d7aeb67c67338c4d2,40.7109,1.0,783d21d013a7e655bddc4ed0d461cc5e,251 South Third Street\r,"[Roof Deck, Balcony, Elevator, Laundry in Buil..."
100000,6860601,"Midtown West, 8th Ave","~Take a stroll in Central Park, enjoy the ente...",2016-04-12 05:24:17,4900,2,-73.9845,[https://photos.renthop.com/2/6860601_c96164d8...,b5eda0eb31b042ce2124fd9e9fcfce2f,40.7650,2.0,6134e7c4dd1a98d9aee36623c9872b49,260 West 54th Street,"[Common Outdoor Space, Cats Allowed, Dogs Allo..."

In [40]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__hash__',
 '__init__',
 '__iter__',
 '__len__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_get_param_names',
 '_make_estimator',
 '_set_oob_score',
 '_validate_X_predict',
 '_validate_estimator',
 '_validate_y_class_weight',
 'apply',
 'base_estimator',
 'base_estimator_',
 'bootstrap',
 'class_weight',
 'classes_',
 'criterion',
 'decision_path',
 'estimator_params',
 'estimators_',
 'feature_importances_',
 'fit',
 'fit_transform',
 'get_params',
 'max_depth',
 'max_features',
 'max_leaf_nodes',
 'min_impurity_split',
 'min_samples_leaf',
 'min_samples_split',
 'min_weight_fraction_leaf',
 'n_classes_',
 'n_estimators',
 'n_features_',
 'n_jobs',
 'n_outputs_',
 'oob_score',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'random_state',
 'score',
 'set_params',
 'transform',
 'verbose',
 'warm_start']

In [44]:
clf.classes_

array([u'high', u'low', u'medium'], dtype=object)